config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :carousels do
      resources :items, controller: :carousel_items do
        collection do
          post :update_positions
        end
        member do
          put :enable
          put :disable
        end
      end
    end
  end
end

app/models/spree/carousel.rb
module Spree
  class Carousel < Base
    has_many :items, class_name: 'Spree::CarouselItem', foreign_key: :carousel_id, inverse_of: :carousel
    has_many :visible_items, -> { where("visible = true") }, class_name: 'Spree::CarouselItem', foreign_key: :carousel_id, inverse_of: :carousel

    self.whitelisted_ransackable_attributes = %w[description title]
  end
end

app/models/spree/carousel_image.rb
module Spree
  class CarouselImage < Asset
    include Rails.application.config.use_paperclip ? Image::Configuration::Paperclip : Image::Configuration::ActiveStorage
    include Rails.application.routes.url_helpers

    def self.accepted_image_types
      %w(image/jpeg image/jpg image/png image/gif)
    end

    if Rails.application.config.use_paperclip
      has_attached_file :attachment,
                        styles: {mini: '125x50>', small: '250x100>', product: '500x200>', large: '750x300>', gigantic: '1000x400>'},
                        default_style: :large,
                        url: '/spree/carousels/:id/:style/:basename.:extension',
                        path: ':rails_root/public/spree/carousels/:id/:style/:basename.:extension',
                        convert_options: {all: '-strip -auto-orient -colorspace sRGB'}
      validates_attachment :attachment,
                           presence: true,
                           content_type: {content_type: accepted_image_types}

      # if there are errors from the plugin, then add a more meaningful message
      def no_attachment_errors
        unless attachment.errors.empty?
          # uncomment this to get rid of the less-than-useful interim messages
          # errors.clear
          errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
          false
        end
      end
    else
      def self.styles
        @styles ||= {
            mini: '125x50>', small: '250x100>', product: '500x200>', large: '750x300>', gigantic: '1000x400>'
        }
      end

      def default_style
        :large
      end

      def url(size = default_style)
        style = self.class.styles[size] || self.class.styles[default_style]
        polymorphic_path(attachment.variant(resize: style), only_path: true)
      end
    end
  end
end

app/models/spree/carousel_item.rb
module Spree
  class CarouselItem < Base
    default_scope -> { order("position asc") }
    acts_as_list scope: :carousel

    belongs_to :carousel, class_name: 'Spree::Carousel', inverse_of: :items
    has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::CarouselImage'
  end
end

app/controllers/spree/admin/carousel_items_controller.rb
module Spree
  module Admin
    class CarouselItemsController < ResourceController
      belongs_to 'spree/carousel'

      def enable
        invoke_callbacks(:enable, :before)
        if @object.update_attributes(visible: true)
          invoke_callbacks(:enable, :after)
          respond_with(@object) do |format|
            format.html do
              flash[:success] = flash_message_for(@object, :successfully_updated)
              redirect_to edit_admin_carousel_path(@parent)
            end
            format.js {render layout: false}
          end
        else
          invoke_callbacks(:update, :fails)
          respond_with(@object) do |format|
            format.html {render action: :edit}
            format.js {render layout: false}
          end
        end
      end

      def disable
        invoke_callbacks(:disable, :before)
        if @object.update_attributes(visible: false)
          invoke_callbacks(:disable, :after)
          respond_with(@object) do |format|
            format.html do
              flash[:success] = flash_message_for(@object, :successfully_updated)
              redirect_to edit_admin_carousel_path(@parent)
            end
            format.js {render layout: false}
          end
        else
          invoke_callbacks(:update, :fails)
          respond_with(@object) do |format|
            format.html {render action: :edit}
            format.js {render layout: false}
          end
        end
      end

      def create
        invoke_callbacks(:create, :before)

        p = permitted_resource_params
        i = p[:image]
        p.delete(:image)

        unless i.nil?
          image = @object.build_image
          image.attributes = i
        end

        @object.attributes = permitted_resource_params
        if @object.save
          invoke_callbacks(:create, :after)
          flash[:success] = flash_message_for(@object, :successfully_created)
          respond_with(@object) do |format|
            format.html {redirect_to edit_admin_carousel_path(@parent)}
            format.js {render layout: false}
          end
        else
          invoke_callbacks(:create, :fails)
          respond_with(@object) do |format|
            format.html {render action: :new}
            format.js {render layout: false}
          end
        end
      end

      def update
        invoke_callbacks(:update, :before)

        p = permitted_resource_params

        i = p[:image]
        p.delete(:image)

        unless i.nil?
          image = @object.build_image
          image.attributes = i
        end

        if @object.update_attributes(permitted_resource_params)
          invoke_callbacks(:update, :after)
          respond_with(@object) do |format|
            format.html do
              flash[:success] = flash_message_for(@object, :successfully_updated)
              redirect_to edit_admin_carousel_path(@parent)
            end
            format.js {render layout: false}
          end
        else
          invoke_callbacks(:update, :fails)
          respond_with(@object) do |format|
            format.html {render action: :edit}
            format.js {render layout: false}
          end
        end

      end

      protected

      def build_resource
        if parent_data.present?
          parent.send(:items).build
        else
          model_class.new
        end
      end

      def find_resource
        if parent_data.present?
          parent.send(:items).find(params[:id])
        else
          model_class.find(params[:id])
        end
      end
    end
  end
end

app/controllers/spree/admin/carousels_controller.rb
module Spree
  module Admin
    class CarouselsController < ResourceController
      include ActionView::Helpers::UrlHelper
      helper_method :toggle_visibility_link


      def model_class
        Spree::Carousel
      end

      def create
        invoke_callbacks(:create, :before)

        @object.record = Spree::Variant.find_by_id(params[:variant_id])
        @object.attributes = permitted_resource_params

        if @object.valid?
          super
        else
          invoke_callbacks(:create, :fails)
          flash[:error] = @object.errors.full_messages.join(", ")
          redirect_to location_after_save
        end
      end

      protected

      def toggle_visibility_link(resource)
        if resource.visible
          url = disable_admin_carousel_item_path(@object, resource)
          icon_name = 'eye-close'
        else
          url = enable_admin_carousel_item_path(@object, resource)
          icon_name = 'eye-open'
        end

        css = "btn btn-outline-secondary btn-sm icon-link with-tip action-#{icon_name}"
        icon = content_tag(:span, '', class: "icon icon-#{icon_name}")
        link_to(icon.html_safe, url, { class: css, data: { method: "put" } })
      end

      def location_after_save
        spree.admin_product_attachments_path(@product)
      end

      def permitted_resource_params
        params.require(:attachment).permit(permitted_digital_attributes)
      end

      def permitted_digital_attributes
        [:bucket, :key, :filename]
      end

      def collection
        return @collection if @collection.present?
        # params[:q] can be blank upon pagination
        params[:q] = {} if params[:q].blank?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
            page(params[:page]).
            per(50)
      end

    end
  end
end

app/helpers/spree/carousels_helper.rb
module Spree
  module CarouselsHelper
    def render_carousel(name)
      # noinspection RailsChecklist05
      carousel = Spree::Carousel.find_by_title name
      @carousel = []
      @carousel = carousel.visible_items unless carousel.nil?
      render partial: "spree/carousels/carousel"
    end
  end
end

app/views/spree/admin/carousel_items/edit.html.erb
<div class="container">
  <%= form_for [:admin, @object], url: admin_carousel_item_path(@parent, @object), method: :put, html: { multipart: true } do |f| %>
    <div data-hook="admin_carousel_item_form_image">
      <%= image_tag @object.image.url(:original) unless @object.image.nil? %>
      <%= f.fields_for :image, @object.image do |i| %>
        <div class="form-group">
          <%= i.label :attachment, Spree.t(:upload) %>
          <%= i.file_field :attachment, class: 'form-control' %>
        </div>
      <% end %>
    </div>
    <div data-hook="admin_carousel_item_form_link">
      <%= f.field_container :link, class: ['form-group'] do %>
        <%= f.label :link, Spree.t(:link) %>
        <%= f.text_field :link, class: 'form-control' %>
      <% end %>
    </div>
    <div data-hook="admin_carousel_item_form_content">
      <%= f.field_container :content, class: ['form-group'] do %>
        <%= f.label :content, Spree.t(:content) %>
        <%= f.text_area :content, { rows: "2", class: 'form-control' } %>
        <%= f.error_message_on :content %>
      <% end %>
    </div>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh', 'submit', { class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." } } %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), edit_admin_carousel_path(@parent), icon: 'delete' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/carousel_items/new.html.erb
<div class="container">
  <%= form_for [:admin, @object], url: admin_carousel_items_path(@parent), method: :post, html: {multipart: true} do |f| %>
    <div data-hook="admin_carousel_item_form_image">
      <%= image_tag @object.image.url(:original) unless @object.image.nil? %>
      <%= f.fields_for :image, @object.image do |i| %>
        <div class="form-group">
          <%= i.label :attachment, Spree.t(:upload) %>
          <%= i.file_field :attachment, class: 'form-control' %>
        </div>
      <% end %>
    </div>
    <div data-hook="admin_carousel_item_form_link">
      <%= f.field_container :link, class: ['form-group'] do %>
        <%= f.label :link, Spree.t(:link) %>
        <%= f.text_field :link, class: 'form-control' %>
      <% end %>
    </div>
    <div data-hook="admin_carousel_item_form_content">
      <%= f.field_container :content, class: ['form-group'] do %>
        <%= f.label :content, Spree.t(:content) %>
        <%= f.text_area :content, {rows: "2", class: 'form-control'} %>
        <%= f.error_message_on :content %>
      <% end %>
    </div>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh', 'submit', {class: 'btn-success', data: {disable_with: "#{ Spree.t(:saving) }..."}} %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), edit_admin_carousel_path(@parent), icon: 'delete' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/carousels/edit.html.erb
<% content_for :page_actions do %>
  <% if frontend_available? %>
    <%= button_link_to Spree.t(:preview_carousel), product_url(@carousel), {class: "btn-default", icon: 'eye-open', id: 'admin_preview_carousel', target: :_blank} %>
  <% end %>
  <% if can?(:create, Spree::Carousel) %>
    <%= button_link_to Spree.t(:new_carousel), new_object_url, {class: "btn-success", icon: 'add', id: 'admin_new_carousel'} %>
  <% end %>
<% end %>

<%= form_for [:admin, @carousel] do |f| %>
  <fieldset>
    <div data-hook="admin_carousel_edit_form">
      <div class="row">
        <div data-hook="admin_carousel_form_fields" class="col-xs-12 col-md-6">
          <div class="form-group" data-hook="sku">
            <%= f.label :title, Spree.t(:title) %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
  <table class="table sortable" id='listing_carousel_items' data-hook data-sortable-link="<%= update_positions_admin_carousel_items_url @carousel %>">
    <thead>
    <tr data-hook="carousel_items_header">
      <th class="no-border"></th>
      <th></th>
      <th><%= Spree.t(:visible) %></th>
      <th><%= Spree.t(:link) %></th>
      <th><%= Spree.t(:content) %></th>
      <th class="actions"><%= link_to_with_icon 'plus', Spree.t(:new_item), new_admin_carousel_item_path(@carousel), class: 'btn btn-success btn-sm' %></th>
    </tr>
    </thead>
    <tbody>
    <% @carousel.items.each do |item| %>
      <tr id="<%= spree_dom_id item %>" data-hook="carousel_items_row">
        <td class="move-handle">
          <span class="icon icon-sort handle"></span>
        </td>
        <td><%= image_tag item.image.url(:small) unless item.image.nil? %></td>
        <td><%= tag('span', class: 'icon icon-ok') if item.visible %></td>
        <td><%= item.link %></td>
        <td><%= truncate(strip_tags(item.content)) %></td>
        <td class="actions actions-2 text-right">
          <%= toggle_visibility_link(item) if can?(:edit, item) %>
          <%= link_to_edit item.id, no_text: true, url: edit_admin_carousel_item_path(@carousel, item) if can?(:edit, item) %>
          <%= link_to_delete item, no_text: true, url: admin_carousel_item_path(@carousel, item) if can?(:delete, item) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/carousels/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Carousel) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_carousel), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_carousel' } %>
<% end if can?(:create, Spree::Carousel) %>

<% content_for :table_filter do %>
  <div data-hook="admin_carousel_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = { f: f } %>
      <div data-hook="admin_carousel_index_search" class="row">
        <div class="col-xs-12 col-md-6">
          <div class="form-group">
            <%= f.label :title, Spree.t(:name) %>
            <%= f.text_field :title, size: 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
      </div>
      <div data-hook="admin_carousel_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
  <table class="table" id="listing_carousels">
    <thead>
    <tr data-hook="admin_carousels_index_headers">
      <th colspan="2"><%= sort_link @search, :title, Spree.t(:title), { default_order: "desc" }, { title: 'admin_carousels_listing_name_title' } %></th>
      <th data-hook="admin_products_index_header_actions" class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @collection.each do |carousel| %>
      <tr id="<%= spree_dom_id carousel %>" data-hook="admin_carousels_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= link_to carousel.try(:title), edit_admin_carousel_path(carousel) %></td>
        <td class="actions actions-3 text-right" data-hook="admin_carousels_index_row_actions">
          <%= link_to_edit carousel, no_text: true, class: 'edit' if can?(:edit, carousel) %>
          <%= link_to_delete carousel, no_text: true if can?(:delete, carousel) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Carousel)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Carousel) %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/carousels/_carousel.html.erb
<%- cache(@carousel) do -%>
  <div uk-slideshow="ratio: 500:200; animation: push; autoplay: true">
    <div class="uk-position-relative uk-visible-toggle uk-light">
      <ul class="uk-slideshow-items">
        <%= render partial: 'spree/carousels/item', collection: @carousel, as: :item %>
      </ul>
    </div>
    <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>
  </div>
<%- end -%>

app/views/spree/carousels/_item.html.erb
<%- cache(item) do -%>
  <li class="carousel-item<%= item_counter == 1 ? ' active' : '' %>">
    <%= image_tag item.image.attachment.url(:product), class: '', 'uk-cover': '' unless item.image.nil? %>
    <%- unless item.content.nil? %>
      <div class="uk-overlay uk-position-bottom">
        <%= raw item.content %>
      </div>
    <%- end %>
  </li>
<%- end -%>